name: build-tgfocus
run-name: Build TG-Focus
on:
  push:
    branches:
      - master
  
jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "CURR_DATE=$(date +'%Y%m%d')" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install buildah -y
      - name: Prepare TDLib
        run: bash oci/fetch-tdlib.bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build TgFocus
        run: bash oci/build-app.bash
      - name: Package TgFocus
        if: contains(github.event.head_commit.message, 'bWFrZS1hcnRpZmFjdAo=') == true
        run: bash oci/package-app.bash
      - name: OCI Image
        if: contains(github.event.head_commit.message, 'bWFrZS1hcnRpZmFjdAo=') == true
        uses: actions/upload-artifact@v3
        with:
          name: tg-focus-ociapp-${{ env.CURR_DATE }}
          path: |
            tg-focus-ociapp-*





      